[package]
name = "game_chess"
version = "0.0.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/game_chess"
repository = "https://github.com/Wandalen/game_chess/"
homepage = "https://github.com/Wandalen/game_chess/"
description = """
Neutral cross-platform Rust game template.
"""
categories = [ "game-development", "game-engines" ]
keywords = [ "chess", "gamedev" ]
default-run = "boardtop"
include = [
  "/src",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
web = [ "bevy/bevy_gltf", "bevy/bevy_winit", "bevy/render", "bevy/png" ]
boardtop = []
default = [ "boardtop" ]

[lib]
name = "game_chess"
crate-type = [ "staticlib", "lib", "cdylib" ]
path = "./src/main.rs"

[[bin]]
name = "web"
path = "./src/main.rs"
required-features = [ "web" ]

[[bin]]
name = "boardtop"
path = "./src/main.rs"

[dependencies]
game_chess_core = { version = "~0.0", path = "../core" }

[target.'cfg( not ( target_arch = "wasm32" ) )'.dependencies]
bevy = { version = "0.5" }

[target.'cfg( target_arch = "wasm32" )'.dependencies]
bevy = { version = "0.5", default-features = false }
tracing-wasm = "=0.2.0"
bevy_webgl2 = "0.5"

