[package]
name = "multiplayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.6"
tonic = "0.6"
prost = "0.9"

[build-dependencies]
tonic-build = "0.6"
