
name: Beta

on :
  pull_request :
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:

  desktop:
    uses: Wandalen/game_chess/.github/workflows/DesktopCommon.yml@main
    with:
      artifacts: 'false'
      build: 'fast'
      toolchain: 'stable'
  web:
    uses: Wandalen/game_chess/.github/workflows/WebCommon.yml@main
    with:
      artifacts: 'false'
      build: 'fast'
      toolchain: 'nightly'
