
name : Deploy

on :
  push:
    branches : [ main ]

env:
  CARGO_TERM_COLOR: always

jobs :
  artifacts_forward :
    runs-on : ubuntu-latest
    steps :
      - name: Build server and web on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRIVATE_SERVER_HOST }}
          username: ${{ secrets.PRIVATE_SERVER_USER }}
          key: ${{ secrets.PRIVATE_SERVER_PRIVATE_KEY }}
          command_timeout: 60m
          script: |
            git clone https://github.com/Wandalen/game_chess.git chess_mirror
            cd chess_mirror
            git pull
            ~/.cargo/bin/cargo build --bin server --release
            cp target/release/server target/chess_server
            ~/.cargo/bin/cargo make web_build_release
            cp -R target/web/* ${{ secrets.PRIVATE_SERVER_PATH }}

