
name : Deploy

on :
  push:
    branches : [ deploy ]

env:
  CARGO_TERM_COLOR: always

jobs :

  artifacts_forward :
    runs-on : ubuntu-latest
    steps :
      - name: Build server and web on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRIVATE_SERVER_HOST }}
          username: ${{ secrets.PRIVATE_SERVER_USER }}
          key: ${{ secrets.PRIVATE_SERVER_PRIVATE_KEY }}
          command_timeout: 60m
          script: |
            git clone https://github.com/Wandalen/game_chess.git chess_mirror
            cd chess_mirror
            git checkout deploy
            git pull
            ~/.cargo/bin/cargo build --bin chess_server --release
            ~/.cargo/bin/cargo make web_build_release
            cp -R target/web/* ${{ secrets.PRIVATE_SERVER_PATH }}
            killall chess_server ;
            cp target/release/chess_server ~/chess_server
            nohup ~/chess_server &

