
name : Deploy

on :
  push:
    branches : [ deploy ]

env:
  CARGO_TERM_COLOR: always

jobs :

  # web:
  #   uses: Wandalen/game_chess/.github/workflows/WebCommon.yml@main
  #   with:
  #     artifacts: 'true'
  #     toolchain: 'nightly'

  artifacts_forward :
    # needs: [ web ]
    runs-on : ubuntu-latest
    steps :
      # - uses: actions/checkout@v2
      # - run: rm -rf build
      # - run: mkdir build
      # - name: Install latest toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true
      # - run: sudo apt install libudev-dev libalsa-ocaml-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
      # - run: cargo doc
      # - run: zip -r build/doc.zip target/doc

      # - uses: actions/download-artifact@v2
      #   with:
      #     name: web
      #     path: build


      # - name: host
      #   run: "::set-output name=host::$(echo ${{ secrets.PRIVATE_SERVER }} | cut -d'@' -f1)"
      # - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      #   with:
      #     ssh-private-key: ${{ secrets.PRIVATE_SERVER_PRIVATE_KEY }}
      #     # ssh-host: ${{ steps.host.outputs.host }}
      #     ssh-host: ${{ secrets.PRIVATE_SERVER_HOST}}
      # - run : sudo apt install sshfs
      # - run : mkdir mnt
      # - name : Setup mountpoin
      #   run : sshfs -o follow_symlinks,StrictHostKeyChecking=no ${{ secrets.PRIVATE_SERVER }}:${{ secrets.PRIVATE_SERVER_PRIVATE_KEY }} ./mnt
      # - run : mkdir ./mnt/chess
      # - run : cp -R build/* ./mnt/chess
      # - run : umount ./mnt

      #  ~/.cargo/bin/cargo make web_build_release
      #       cp -R target/web/* ${{ secrets.PRIVATE_SERVER_PATH }}/chess

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRIVATE_SERVER_HOST }}
          username: ${{ secrets.PRIVATE_SERVER_USER }}
          key: ${{ secrets.PRIVATE_SERVER_PRIVATE_KEY }}
          command_timeout: 60m
          script: |
            git clone https://github.com/Wandalen/game_chess.git chess_mirror
            cd chess_mirror
            git pull
            ~/.cargo/bin/cargo build --bin server --release
            cp target/release/server target/server
            ~/.cargo/bin/cargo make web_build_release
            cp -R target/web/* ${{ secrets.PRIVATE_SERVER_PATH }}
      
            
            
