
name : Forward

on :
  push :
    branches : [ alpha ]

env:
  CARGO_TERM_COLOR: always

jobs :

  desktop:
    if: "contains( github.event.head_commit.message, '[build]' ) || startsWith( github.event.head_commit.message, 'Merge ' )"
    uses: Wandalen/game_chess/.github/workflows/DesktopCommon.yml@main
    with:
      artifacts: 'true'
  web:
    if: "contains( github.event.head_commit.message, '[build]' ) || startsWith( github.event.head_commit.message, 'Merge ' )"
    uses: Wandalen/game_chess/.github/workflows/WebCommon.yml@main

  forward :
    needs: [ desktop, web ]
    runs-on : ubuntu-latest
    steps :
      - uses: actions/checkout@v2
      - uses : everlytic/branch-merge@1.1.2
        with :
          github_token : ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          source_ref : alpha
          target_branch : beta
          commit_message_template : 'Merge {source_ref} into {target_branch} [Automated]'

